### ISSUE TITLE
Write script to prepare digitization files

### ISSUE THREAD

**Issue by edwardsmarc** [beaconsproject/disturbance_mapping#1]
Digitization template files will be prepared with columns matching those of YG manual.

Linear disturbance file should be initialized with the NRN road layer. Script should translate the NRN data into our disturbance layer. This layer will then be clipped to the study region boundaries along with all other layer when preparing the project folders.

Is there an equivalent layer we can initialize the areal disturbance layer with? If not, just prepare an empty template file to include in each project folder.

**Comment by prvernier** [comment]
Completed
